<script language="javascript" type="text/javascript">
    $(function() {

        var OnSiteMarker = 0;
        var BorrowMarker = 0;

        if ($('.lt_borrowed_entry').length > 0)  {
            setBorrowedMarker(1);
        }

        function setBorrowedMarker(bool) {
            BorrowMarker = bool;
        }

        function getBorrowedMarker() {
            return BorrowMarker;
        }

        function setOnSiteMarker(bool) {
            OnSiteMarker = bool;
        }

        function getOnSiteMarker() {
            return OnSiteMarker;
        }

        window.onbeforeunload = function (e) {
          if (getOnSiteMarker() != 1 && getBorrowedMarker() == 1) {
              var message = "There are checked out items.",
              e = e || window.event;
              // For IE and Firefox
              if (e) {
                e.returnValue = message;
              }

              // For Safari
              return message;
          }
        };

        $( "#listtool_iframe" ).dialog({
            autoOpen: false,
            height: 550,
            width: 500,
            modal: true
        });

        $("#lt_new_file").click(function() {
            $("#listtool_iframe").html('<iframe frameborder="0" src="<?php echo $this->addurlfile; ?>" width="99%" height="99%" name="new file"></iframe>');
            $( "#listtool_iframe" ).dialog("open");
            return false;
        });
        
        $("#lt_new_link").click(function() {
            $("#listtool_iframe").html('<iframe frameborder="0" src="<?php echo $this->addurllink; ?>" width="99%" height="99%" name="new file"></iframe>');
            $( "#listtool_iframe" ).dialog("open");
            return false;
        });

        $("#lt_sorting").click(function() {
            $("#listtool_iframe").attr("title", "Sortierung");
            $("#listtool_iframe").html('<iframe frameborder="0" src="<?php echo $this->sorturl; ?>" width="99%" height="99%" name="new file"></iframe>');
            $("#listtool_iframe").dialog("open");
            return false;
        });

        $(".lt_edit_entry").click(function() {
            var ltid = $(this).attr('id').replace(/lt_entry_/g, "");
            $("#listtool_iframe").html('<iframe frameborder="0" src="<?php echo $this->baseurl; ?>&cmd=showEditEntryForm&id='+ltid+'" width="99%" height="99%" name="new file"></iframe>');
            $("#listtool_iframe").dialog("open");
            return false;
        });
        
        $(".lt_start_approval_entry").click(function() {
            var ltid = $(this).attr('id').replace(/lt_entry_/g, "");
            $("#listtool_iframe").html('<iframe frameborder="0" src="<?php echo $this->baseurl; ?>&cmd=showStartApprovalEntryForm&id='+ltid+'" width="99%" height="99%" name="new file"></iframe>');
            $("#listtool_iframe").dialog("open");
            return false;
        });
        
        $(".lt_status_approval_entry").click(function() {
            var ltid = $(this).attr('id').replace(/lt_entry_/g, "");
            $("#listtool_iframe").html('<iframe frameborder="0" src="<?php echo $this->baseurl; ?>&cmd=showApprovalEntryStatus&id='+ltid+'" width="99%" height="99%" name="new file"></iframe>');
            $("#listtool_iframe").dialog("open");
            return false;
        });
        
        $(".lt_vote_approval_entry").click(function() {
            var ltid = $(this).attr('id').replace(/lt_entry_/g, "");
            $("#listtool_iframe").html('<iframe frameborder="0" src="<?php echo $this->baseurl; ?>&cmd=showApprovalEntryVote&id='+ltid+'" width="99%" height="99%" name="new file"></iframe>');
            $("#listtool_iframe").dialog("open");
            return false;
        });

        $(".lt_onsite_link").click(function() {
            setOnSiteMarker(1);
            return true;
        });

    });
</script>
<div id="listtool_iframe" title="Listtool">&nbsp;</div>
