<fieldset class="lwadminform">

    <legend class="lwadminform">Schwerwiegender Fehler</legend>
       
    <div class="lw_form">
        <div class="lw_infobox">
            <span>Der Pfad für die Listtool-Dateien existiert nicht und konnte nicht angelegt werden! Bitte wenden sie sich an den Administrator.</span>
            <br/><br/>
            <a href="<?php echo $this->backUrl; ?>">zurück zur Übersicht!</a>
        </div>
    </div>	        
	
</fieldset>        