<div id="chart1" class="pieChart"></div>

<script>
      var data = <?php echo "[['yes', ".$this->yes."],['no', ".$this->no."]]"; ?>;          
      var plot1 = jQuery.jqplot ('chart1', [data],
        {
          //title: 'echo $this->title',           
          seriesDefaults: {
            // Make this a pie chart.
            renderer: jQuery.jqplot.PieRenderer,
            rendererOptions: {
              // Put data labels on the pie slices.
              // By default, labels show the percentage of the slice.
              showDataLabels: true,
              seriesColors: [ "#788eff", "#fffa78", "#b8f5fb", "#aeff78", "#cb78ff", "#ff7878", "#ffbb78", "#d4ff78", "#78ffa4", "#ab78ff" ]
            }
          }
        });
</script>