<style>
    div.lwlt_list table tr td, div.lwlt_list table tr, div.lwlt_list table {
        border-collapse:collapse;
    }
    
    div.lwlt_list table {
        border:0px;
    }
    
    div.lwlt_list table tr td, div.lwlt_list table tr th {
        border-left:0px;
        border-right:0px;
        border-bottom:1px solid grey;
        text-align:left;
        padding:2px;
        vertical-align: top;
    }
    
    div.lwlt_list table tbody tr:nth-child(odd) { background-color:#f3f3f3; }
    div.lwlt_list table tbody tr:nth-child(even) { background-color:#fff; }
    
    div.lt_adminfunctions {
        margin-bottom:15px;
    }
    
</style>
<h2>Versionen der Datei "Protokoll vom 13.07.2012"</h2>
<div>
    <a href="index.php?index=151">zur&uuml;ck zur Liste</a>
</div>
<br/>
<div class="lwlt_list">
    <table width="100%" border="1">
        <thead>
            <tr>
                <th align="left">
                    Datum
                </th>
                <th align="left">
                    Benutzer
                </th>
                <th align="left">
                    Funktionen
                </th>
            </tr>
        </thead>
        <tbody> 
            <tr>
                <td>
                    14.07.2012
                </td>
                <td>
                    Max Mustermann
                </td>
                <td>
                    <a href="">download</a><span style="display:none;"> | <a href="" onclick="return confirm('wirklich reaktivieren und damit die aktuelle Version archivieren?');">reaktivieren</a> | <a href="" onclick="return confirm('wirklich l&ouml;schen?');">endgültig löschen</a></span>
                </td>
            </tr>
            <tr>
                <td>
                    17.07.2012
                </td>
                <td>
                    Foo Bar
                </td>
                <td>
                    <a href="">download</a><span style="display:none;"> | <a href="">reaktivieren</a> | <a href="">endgültig löschen</a></span>
                </td>
            </tr>
            <tr>
                <td>
                    05.08.2012
                </td>
                <td>
                    Max Mustermann
                </td>
                <td>
                    <a href="">download</a><span style="display:none;"> | <a href="">reaktivieren</a> | <a href="">endgültig löschen</a></span>
                </td>
            </tr>
        </tbody>
    </table>
</div>

